# -*- coding: utf-8 -*-
"""dio-desafio-etl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bVg3JVlRAIGqrLl5u5GQA_cLcUupy9u6

# Extract
"""

import pandas as pd
import numpy as np
import json

df = pd.read_csv("dados.csv")
df.head()

"""# Transform"""

df = df.rename(columns={'nome': 'nome_completo'})

df['idade'] = df['idade'].astype(int)

df

"""# Load"""

#Converta o DataFrame para JSON
json_data = df.to_json()

#Salve o JSON em um arquivo.

with open("data.json", "w") as f:
    f.write(json_data)

df2= pd.read_json(json_data)

print(df2)